services:
  postgres:
    image: postgres:16
    container_name: controla-gastos-db
    environment:
      POSTGRES_DB: controlagastos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: controla-gastos-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/controlagastos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: controla-gastos-web
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
